"""Add server_id to metrics tables

Revision ID: a2ee97cdc336
Revises: 20a0e0538ac5
Create Date: 2026-03-20 14:44:40.333197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ee97cdc336'
down_revision: Union[str, Sequence[str], None] = '20a0e0538ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Make migration idempotent: check if tables and columns exist before modifying
    inspector = sa.inspect(op.get_bind())

    # Skip if tables don't exist (fresh DB uses db.py models directly)
    table_names = inspector.get_table_names()
    if 'tool_metrics' not in table_names:
        return

    # Check if server_id already exists in tool_metrics (proxy for all tables)
    tool_metrics_columns = [col['name'] for col in inspector.get_columns('tool_metrics')]
    if 'server_id' in tool_metrics_columns:
        return  # Already applied

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('idx_prompt_metrics_prompt_id_timestamp'), table_name='prompt_metrics')
    op.create_index(op.f('ix_prompt_metrics_server_id'), 'prompt_metrics', ['server_id'], unique=False)
    op.add_column('prompt_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_prompt_metrics_hourly_prompt_hour'), 'prompt_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_prompt_metrics_hourly_server_id'), 'prompt_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_prompt_metrics_hourly_prompt_server_hour', 'prompt_metrics_hourly', ['prompt_id', 'server_id', 'hour_start'])
    op.add_column('resource_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('idx_resource_metrics_resource_id_timestamp'), table_name='resource_metrics')
    op.create_index(op.f('ix_resource_metrics_server_id'), 'resource_metrics', ['server_id'], unique=False)
    op.add_column('resource_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_resource_metrics_hourly_resource_hour'), 'resource_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_resource_metrics_hourly_server_id'), 'resource_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_resource_metrics_hourly_resource_server_hour', 'resource_metrics_hourly', ['resource_id', 'server_id', 'hour_start'])
    op.drop_index(op.f('idx_server_metrics_server_id_timestamp'), table_name='server_metrics')
    op.add_column('tool_metrics', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('idx_tool_metrics_tool_id_timestamp'), table_name='tool_metrics')
    op.create_index(op.f('ix_tool_metrics_server_id'), 'tool_metrics', ['server_id'], unique=False)
    op.add_column('tool_metrics_hourly', sa.Column('server_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_tool_metrics_hourly_tool_hour'), 'tool_metrics_hourly', type_='unique')
    op.create_index(op.f('ix_tool_metrics_hourly_server_id'), 'tool_metrics_hourly', ['server_id'], unique=False)
    op.create_unique_constraint('uq_tool_metrics_hourly_tool_server_hour', 'tool_metrics_hourly', ['tool_id', 'server_id', 'hour_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_metrics_hourly_tool_server_hour', 'tool_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_tool_metrics_hourly_server_id'), table_name='tool_metrics_hourly')
    op.create_unique_constraint(op.f('uq_tool_metrics_hourly_tool_hour'), 'tool_metrics_hourly', ['tool_id', 'hour_start'], postgresql_nulls_not_distinct=False)
    op.drop_column('tool_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_tool_metrics_server_id'), table_name='tool_metrics')
    op.create_index(op.f('idx_tool_metrics_tool_id_timestamp'), 'tool_metrics', ['tool_id', 'timestamp'], unique=False)
    op.drop_column('tool_metrics', 'server_id')
    op.create_index(op.f('idx_server_metrics_server_id_timestamp'), 'server_metrics', ['server_id', 'timestamp'], unique=False)
    op.drop_constraint('uq_resource_metrics_hourly_resource_server_hour', 'resource_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_resource_metrics_hourly_server_id'), table_name='resource_metrics_hourly')
    op.create_unique_constraint(op.f('uq_resource_metrics_hourly_resource_hour'), 'resource_metrics_hourly', ['resource_id', 'hour_start'], postgresql_nulls_not_distinct=False)
    op.drop_column('resource_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_resource_metrics_server_id'), table_name='resource_metrics')
    op.create_index(op.f('idx_resource_metrics_resource_id_timestamp'), 'resource_metrics', ['resource_id', 'timestamp'], unique=False)
    op.drop_column('resource_metrics', 'server_id')
    op.drop_constraint('uq_prompt_metrics_hourly_prompt_server_hour', 'prompt_metrics_hourly', type_='unique')
    op.drop_index(op.f('ix_prompt_metrics_hourly_server_id'), table_name='prompt_metrics_hourly')
    op.create_unique_constraint(op.f('uq_prompt_metrics_hourly_prompt_hour'), 'prompt_metrics_hourly', ['prompt_id', 'hour_start'], postgresql_nulls_not_distinct=False)
    op.drop_column('prompt_metrics_hourly', 'server_id')
    op.drop_index(op.f('ix_prompt_metrics_server_id'), table_name='prompt_metrics')
    op.create_index(op.f('idx_prompt_metrics_prompt_id_timestamp'), 'prompt_metrics', ['prompt_id', 'timestamp'], unique=False)
    op.drop_column('prompt_metrics', 'server_id')
    # ### end Alembic commands ###
